// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	entity "service-routes/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// IRepositoryResource is an autogenerated mock type for the IRepositoryResource type
type IRepositoryResource struct {
	mock.Mock
}

// AddResource provides a mock function with given fields: resource
func (_m *IRepositoryResource) AddResource(resource entity.Resource) (*entity.Resource, error) {
	ret := _m.Called(resource)

	var r0 *entity.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Resource) (*entity.Resource, error)); ok {
		return rf(resource)
	}
	if rf, ok := ret.Get(0).(func(entity.Resource) *entity.Resource); ok {
		r0 = rf(resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(entity.Resource) error); ok {
		r1 = rf(resource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DelResource provides a mock function with given fields: idResource
func (_m *IRepositoryResource) DelResource(idResource int64) error {
	ret := _m.Called(idResource)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(idResource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOneResource provides a mock function with given fields: idResource
func (_m *IRepositoryResource) FindOneResource(idResource int64) (*entity.Resource, error) {
	ret := _m.Called(idResource)

	var r0 *entity.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*entity.Resource, error)); ok {
		return rf(idResource)
	}
	if rf, ok := ret.Get(0).(func(int64) *entity.Resource); ok {
		r0 = rf(idResource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(idResource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIRepositoryResource interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRepositoryResource creates a new instance of IRepositoryResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRepositoryResource(t mockConstructorTestingTNewIRepositoryResource) *IRepositoryResource {
	mock := &IRepositoryResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
